version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nutripet
      MONGO_INITDB_ROOT_PASSWORD: tepirtun

volumes:
  mongo-data: