version: '3.8'

services:
  tutor-api-mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: tutor-api-mongo
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo-data: